name: core_network
description: A starting point for Dart libraries or applications.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_foundation:
    path: ../foundation
  core_repository:
    path: ../repository
  core_utility:
    path: ../utility
  core_service:
    path: ../service
  core_di_provider:
    path: ../di_provider
  intl: ^0.19.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.5
  riverpod_annotation: 2.6.1
  riverpod_generator: ^2.6.3
  flutter_riverpod: ^2.6.1
  talker_flutter:
  talker_dio_logger:
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator:

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
