name: core_service
description: A starting point for Dart libraries or applications.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_repository:
    path: ../repository
  core_utility:
    path: ../utility
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.0.0
  riverpod_annotation: 2.6.1
  riverpod_generator: ^2.6.3
  rxdart: ^0.28.0
  firebase_in_app_messaging: ^0.8.0+10
  pretty_dio_logger: ^1.4.0
  flutter_riverpod: ^2.6.1
  flutter_local_notifications: ^17.2.3

  timezone: ^0.9.4
  flutter_timezone:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^6.0.0
