name: melos_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  core_ui:
    path: ../../packages/ui
  core_utility:
    path: ../../packages/utility
  core_di_provider:
    path: ../../packages/di_provider
  core_service:
    path: ../../packages/service
  core_foundation:
    path: ../../packages/foundation
  core_repository:
    path: ../../packages/repository
  core_test_util:
    path: ../../packages/test_util
  core_network:
    path: ../../packages/network
  introduction_screen: ^3.1.14
  timeago: ^3.7.0
  mockito: ^5.4.4
  dio: ^5.7.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.0.0
  firebase_crashlytics: ^4.1.3
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.6.1
  flutter_localization:
  package_info_plus: ^8.1.1
  go_router: ^14.2.8
  go_router_builder: ^2.7.1
  riverpod_annotation: 2.6.1
  riverpod_generator: ^2.6.3
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  riverpod: ^2.6.1
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.2
  connectivity_plus: ^6.1.0
  patrol:
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  cider: ^0.2.8
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/icons/
    - assets/images/introduction/
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
          weight: 100
        - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
          weight: 300
        - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  assets:
    - ./assets/images/
    - ./assets/images/icons/dev.png
    - ./assets/images/icons/prod.png
    - ./assets/images/icons/stg.png

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splash.png"
  color_dark: "#000000"
  image_dark: "assets/images/splash.png"
  fullscreen: false
  android_12:
    icon_background_color: "#000000"
    image: "assets/images/splash.png"
    icon_background_color_dark: "#000000"
    image_dark: "assets/images/splash.png"

patrol:
  app_name: melos_template
  android:
    package_name: com.example.melos_template
  ios:
    bundle_id: com.example.melos_template
  macos:
    bundle_id: com.example.melos_template
