name: core_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  core_foundation:
    path: ../foundation
  core_di_provider:
    path: ../di_provider
  core_utility:
    path: ../utility
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  go_router: ^14.2.8
  riverpod_annotation: 2.6.1

  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
