name: core_di_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  cloud_firestore: ^5.4.3
  talker_dio_logger: ^4.4.1
  connectivity_plus: ^6.0.5
  device_info_plus: ^11.1.1
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.3.2
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  package_info_plus: ^8.0.0
  riverpod_annotation: 2.6.1
  riverpod_generator: ^2.6.3
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
