name: core_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  core_di_provider:
    path: ../di_provider
  core_foundation:
    path: ../foundation

  core_utility:
    path: ../utility
  core_test_util:
    path: ../test_util
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  riverpod_annotation: 2.6.1
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  flutter_riverpod: ^2.6.1
  riverpod_generator: ^2.6.3
  freezed_annotation: ^2.4.4
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  firebase_messaging: ^15.0.0
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
