name: core_test_util
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.6.1
  mockito: ^5.4.4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
